
services:
  postgres:
    env_file: .env.local
    image: postgres:15-alpine
    container_name: localmart-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-localmart}
      POSTGRES_USER: ${POSTGRES_USER:-catalog_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-catalog_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  catalog:
    env_file: .env.local
    build:
      context: ./services/catalog
      dockerfile: Dockerfile
    ports:
      - "${CATALOG_PORT:-8080}:8080"
    container_name: localmart-catalog
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-catalog_user}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-catalog_password}
      DB_NAME: ${POSTGRES_DB:-localmart}
      TRACING_ENABLED: ${TRACING_ENABLED:-false}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-}
    depends_on:
      - postgres

  frontend:
    env_file: .env.local
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_INTERNAL_PORT:-80}"
    container_name: localmart-frontend
    restart: unless-stopped
    depends_on:
      - catalog

volumes:
  postgres_data: