
services:
  postgres:
    env_file: .env.local
    image: postgres:15-alpine
    container_name: localmart-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-localmart}
      POSTGRES_USER: ${POSTGRES_USER:-catalog_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-catalog_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-users:
    env_file: .env.local
    image: postgres:15-alpine
    container_name: localmart-postgres-users
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${USERS_POSTGRES_DB:-localmart_users}
      POSTGRES_USER: ${USERS_POSTGRES_USER:-users_user}
      POSTGRES_PASSWORD: ${USERS_POSTGRES_PASSWORD:-users_password}
    ports:
      - "${USERS_POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data

  catalog:
    env_file: .env.local
    build:
      context: ./services/catalog
      dockerfile: Dockerfile
    ports:
      - "${CATALOG_PORT:-8080}:8080"
    container_name: localmart-catalog
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-catalog_user}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-catalog_password}
      DB_NAME: ${POSTGRES_DB:-localmart}
      TRACING_ENABLED: ${TRACING_ENABLED:-false}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-}
    depends_on:
      - postgres

  users:
    env_file: .env.local
    build:
      context: ./services/users
      dockerfile: Dockerfile
    ports:
      - "${USERS_PORT:-8081}:8081"
    container_name: localmart-users
    restart: unless-stopped
    environment:
      USERS_DB_HOST: postgres-users
      USERS_DB_PORT: 5432
      USERS_DB_USER: ${USERS_POSTGRES_USER:-users_user}
      USERS_DB_PASSWORD: ${USERS_POSTGRES_PASSWORD:-users_password}
      USERS_DB_NAME: ${USERS_POSTGRES_DB:-localmart_users}
      USERS_JWT_SECRET_KEY: ${USERS_JWT_SECRET_KEY:-change-this-secret-key-in-production}
    depends_on:
      - postgres-users

  frontend:
    env_file: .env.local
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_INTERNAL_PORT:-80}"
    container_name: localmart-frontend
    restart: unless-stopped
    depends_on:
      - catalog
      - users

volumes:
  postgres_data:
  postgres_users_data: